HVAC Backup 2/objects/Exception_Log__c.object
<CustomObject>
    <fields>
        <fullName>Cause__c</fullName>
        <label>Cause</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logged_At__c</fullName>
        <label>Logged At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Logged_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Logged By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MPS_Exception_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>ErrorLog-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HVAC Backup 2/classes/GenesysIVRTicketCreationAPI.cls
/**
 * @Author : Sumukha N S
    @CreatedDate : 8th Feb 2024
    @Description : 
    @Last Modified By : Sumukha N S

 */@RestResource(urlMapping='/ivr/createticket')
global with sharing class GenesysIVRTicketCreationAPI {

    @HttpPost
    global static GenesysIVRTicketCreationAPIRespWrapper createTicket() {
      
        String ticketNumber;
        
          // Obtain the incoming REST request and response objects.
          RestRequest req = RestContext.request;
          RestResponse res = RestContext.response;
  
          // Initialize the response wrapper for the API.
          GenesysIVRTicketCreationAPIRespWrapper resp = new GenesysIVRTicketCreationAPIRespWrapper();

        try {
            // Retrieve the JSON request body from the incoming request.
            String jsonReqBody = req.requestBody.toString();
            
            // Attempt to create a new case based on the provided JSON request body.
            ticketNumber = GenesysIVRCaseCreationClass.createNewCase(jsonReqBody);

            

            // Check if case creation was successful.
            if(ticketNumber != null){
                resp.result = IntegrationAPIHelper.RESP_SUCCESS_RESULT;
                resp.message = IntegrationAPIHelper.RESP_SUCCESS_RESPONSE;
                resp.ticket_number = ticketNumber;
            }
            else {
                // Case creation failed.
                resp.result = IntegrationAPIHelper.RESP_FAILURE_RESULT;
                resp.message = IntegrationAPIHelper.RESP_FAILURE_RESPONSE + ticketNumber;
                resp.ticket_number = null;
            }
        } 
        catch (Exception e) {
            // Exception occurred during case creation.

            //insert exception log in the system
            //Exception_Log__c log = new Exception_Log__c();

            //log.Cause__c = String.valueOf(e.getCause());
            //log.Line_Number__c = String.valueOf(e.getLineNumber());
            //log.Logged_At__c = System.now();
            //log.Logged_By__c = UserInfo.getUserId();
            //log.Stack_Trace__c = e.getStackTraceString();
            //log.Error_Message__c = e.getTypeName() + e.getMessage();
            // insert log;

            //send the failed response
            resp.result = IntegrationAPIHelper.RESP_FAILURE_RESULT;
            resp.message = IntegrationAPIHelper.RESP_FAILURE_RESPONSE + '-' +e.getTypeName() + e.getMessage(); 
            resp.ticket_number = ticketNumber;

            System.debug('Exception' + e.getTypeName() + e.getMessage());

        }

        // Return the response wrapper.
        return resp;   

    }
}