HVAC Backup 2/objects/Locality_SubLocality_Data__c.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <label>Locality</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <label>Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Locality__c</fullName>
        <label>Sub Locality</label>
        <type>TextArea</type>
    </fields>
    <label>Locality/SubLocality Data</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Locality/SubLocality Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locality/SubLocality Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HVAC Backup 2/objects/PinCode__c.object
<CustomObject>
    <fields>
        <fullName>Locality__c</fullName>
        <label>Locality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <externalId>true</externalId>
        <label>Postal Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Locality__c</fullName>
        <label>Sub Locality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PinCode</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Pincode Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PinCodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HVAC Backup 2/classes/AddressFormCtrl.cls
public class AddressFormCtrl{
    @AuraEnabled(cacheable=true)
    public static Map<String, String> getCityAndStateByPinCode(String pinCode) {
        Map<String, String> result = new Map<String, String>();
        //call mapMyIndia api 

        //result.put('state', 'Unknown State');
        result = callMappelsPinCodeService(pinCode);
        system.debug(result);
        return result;
    }

    public static  Map<String, String>  callMappelsPinCodeService(String pinCode){
        HttpRequest oRequest = new HttpRequest();
        HTTPResponse oResponse = new HTTPResponse();
        Http oHttp = new Http();
        oRequest.setEndpoint('callout:PostalCodeAPI/'+pinCode);
        oRequest.setMethod('GET');
        oRequest.setHeader('Content-Type','application/x-www-form-urlencoded');  
        oResponse = oHttp.send(oRequest);
        System.debug('Body ' + oResponse.getBody());
         if (oResponse.getStatusCode() == 200) {
            Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(oResponse.getBody());
            Map<String, String> result = new Map<String, String>();
             if(responseMap.containsKey('city') && responseMap.containsKey('state')){
                result.put('city', (String) responseMap.get('city'));
            	result.put('state', (String) responseMap.get('state'));
             } else if(responseMap.containsKey('address')){
                 String address = (String)responseMap.get('address');
                 result.put('city', address.split(',')[0]);
            	 result.put('state', address.split(',')[1]);
             }
             
        	return result;
        } else {
            throw new CalloutException('Failed to get city and state. Response: ' +  oResponse.getBody());
        }
    }

    @AuraEnabled
    public static List<Locality_SubLocality_Data__c> getLocality(String pincode){
        return [Select Id, Locality__c, Sub_Locality__c from Locality_SubLocality_Data__c where pincode__c = : pincode];
    }

    @AuraEnabled
    public static List<PinCode__c> getSector(String pincode){
        return [Select Id, Sector__c from PinCode__c where Postal_Code__c = : pincode and Sector__c != null];
    }
}