HVAC Backup 2/objects/PinCode__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Branch__c</referenceTo>
        <relationshipLabel>PinCodes</relationshipLabel>
        <relationshipName>PinCodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PinCode</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Pincode Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PinCodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HVAC Backup 2/objects/Service_Area_Routing__c.object
<CustomObject>
    <fields>
        <fullName>CP_Code__c</fullName>
        <formula>Channel_Partner__r.CP_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CP Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Channel Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Area Routing</relationshipLabel>
        <relationshipName>Service_Area_Routing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department_Number__c</fullName>
        <formula>Department__r.Department_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Department Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Service Area Routing</relationshipLabel>
        <relationshipName>Service_Area_Routing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pincode</label>
        <referenceTo>PinCode__c</referenceTo>
        <relationshipLabel>Service Area Routing</relationshipLabel>
        <relationshipName>Service_Area_Routing</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Area Routing</label>
    <nameField>
        <displayFormat>SAR-{00000000}</displayFormat>
        <label>Service Area Routing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Area Routing</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

HVAC Backup 2/classes/UniqueServiceAreaRouting.cls
public with sharing class UniqueServiceAreaRouting {
    @InvocableMethod
    public static List<List<Branch_Division__c>> fetchUniqueServiceAreaRouting(List<String> cpCodes) {
        if(cpCodes == null || cpCodes.isEmpty()) {
            return new List<List<Branch_Division__c>>();
        }

        String cpCode = cpCodes[0];

        List<Service_Area_Routing__c> serviceAreaRoutings = [
            SELECT Id, 
                   Pincode__r.Branch__c, 
                   Pincode__r.Branch__r.Branch_Code__c, 
                   Department__c, 
                   Department__r.Department_Number__c, 
                   Channel_Partner__c, 
                   Channel_Partner__r.CP_Code__c 
            FROM Service_Area_Routing__c 
            WHERE Channel_Partner__r.CP_Code__c = :cpCode
        ];

        // Create a Set to store unique pairs
        Set<String> uniquePairs = new Set<String>();

        // Iterate over the records and create unique pairs
        for(Service_Area_Routing__c sar : serviceAreaRoutings) {
            String uniquePair = sar.Pincode__r.Branch__r.Branch_Code__c + '-' + sar.Department__r.Department_Number__c;
            uniquePairs.add(uniquePair);
        }

        // Create a list to store Branch_Division__c records
        List<Branch_Division__c> branchDivisions = new List<Branch_Division__c>();

        // // Query Branch_Division__c records based on unique pairs
        // if (!uniquePairs.isEmpty()) {
        //     List<String> branchCodes = new List<String>();
        //     List<String> departmentNumbers = new List<String>();

        //     // Split unique pairs into branch codes and department numbers
        //     for (String pair : uniquePairs) {
        //         List<String> parts = pair.split('-');
        //         branchCodes.add(parts[0]);
        //         departmentNumbers.add(parts[1]);
        //     }

            branchDivisions = [
                SELECT Id, Branch__r.Branch_Code__c, Department__r.Department_Number__c 
                FROM Branch_Division__c 
                WHERE Branch_Code_Department_Number__c IN : uniquePairs
            ];
             List<List<Branch_Division__c>>  branchDivisionRecords = new List<List<Branch_Division__c>>();
             branchDivisionRecords.add(branchDivisions); 
             return branchDivisionRecords;
        }

        // Return the list of Branch_Division__c records
      
    }