HVAC Backup 2/objects/PMS_Event__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PMS Events</relationshipLabel>
        <relationshipName>PMS_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>PMS Events</relationshipLabel>
        <relationshipName>PMS_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PMS Events</relationshipLabel>
        <relationshipName>PMS_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Skipped__c</fullName>
        <formula>IF(ISPICKVAL(Status__c,&apos;Skipped&apos;),true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Skipped</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMS_Completion_SLA__c</fullName>
        <label>PMS Completion SLA</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PMS_Tickets_Creation_Date__c</fullName>
        <formula>IF( Start_Date__c ==  Asset__r.Standard_Warranty_Start_Date__c, (IF( DAY(Start_Date__c) = 1, Start_Date__c, IF(month(Start_Date__c) == 12, DATE(YEAR( Start_Date__c )+1,1,1), DATE(YEAR( Start_Date__c ),month(Start_Date__c)+1,1)))), (IF( DAY(Start_Date__c) = 1, Start_Date__c, DATE(YEAR( Start_Date__c ),month(Start_Date__c),1))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PMS Tickets Creation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>PMS Events</relationshipLabel>
        <relationshipName>PMS_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>PMS Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Skipped</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Missed</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                    <isActive>false</isActive>
                    <label>Deleted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PMS Event</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>PMS Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMS Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HVAC Backup 2/classes/PMSTicketCreationInvocable.cls
public class PMSTicketCreationInvocable {
	@invocablemethod(label='Create PMS Tickets From Button' description='Creates PMS Tickets From Button' category='Service Contract')
    public static void createPMSTicketsFromButton(List<Id> requests)
    {
        List<PMS_Event__c> pmsEventList = [SELECT Id, PMS_Tickets_Creation_Date__c, Start_Date__c, PMS_Completion_SLA__c, Service_Contract__c,
                                             Asset__c, Contact__c, Account__c, Subject__c, Asset__r.Product_Sub_Family__c, Asset__r.CP__r.CP_User__c, 
                                             Asset__r.CP__c FROM PMS_Event__c WHERE Id =: requests AND Is_Skipped__c = FALSE AND Status__c != 'Cancelled'];
        if(!pmsEventList.isEmpty()){
            SchedulePMSTicketsForContracts.createPMSTicket(pmsEventList);
        }
    }
}