HVAC Backup 2/objects/SMS_Template__c.object
<CustomObject>
    <fields>
        <fullName>Manual_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manual Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Template_Data__c</fullName>
        <label>Template Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>SMS Template</label>
    <nameField>
        <label>SMS Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <label>SMS</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HVAC Backup 2/objects/Template_Variable_Configuration__c(1).object
<CustomObject>
    <fields>
        <fullName>SMS_Template__c</fullName>
        <label>SMS Template</label>
        <referenceTo>SMS_Template__c</referenceTo>
        <relationshipLabel>Template Variable Configurations</relationshipLabel>
        <relationshipName>Template_Variable_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type_of_Object__c</fullName>
        <label>Type of Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>WorkOrder</fullName>
                </value>
                <value>
                    <fullName>ServiceAppointment</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>ReturnOrder</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Survey_Invitation__c</fullName>
                    <label>Survey Invitation</label>
                </value>
                <value>
                    <fullName>Asset</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Variable_Api_Names__c</fullName>
        <label>Variable Api Names</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Template Variable Configuration</label>
    <nameField>
        <label>Template Variable Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template Variable Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HVAC Backup 2/classes/SMSNotificationController.cls
/*
@Author : Himanshi Verma
@CreatedDate : 26th Mar 2024
@Description : It is a controller class for SMSNotification LWC.
*/

public without sharing class  SMSNotificationController {
    @AuraEnabled(cacheable=true)
    public static List<SMS_Template__c> getSMSTemplates(Id recordId) {
        try {
            // Null check for recordId
            if (recordId == null) {
                return null;
            }
            // Retrieve object name
            Schema.DescribeSObjectResult objDescribe = recordId.getSObjectType().getDescribe();
            String objectName = objDescribe.getName();
            //  String query = 'SELECT Name, Template_Data__c, (SELECT Type_of_Object__c, Variable_Api_Names__c FROM Template_Variable_Configurations__r Where Type_of_Object__c =: objectName) FROM SMS_Template__c Where Manual_Trigger__c = TRUE';// this need to be used only commenting for now only
            //  String query = 'SELECT Name, Template_Data__c, (SELECT Type_of_Object__c, Variable_Api_Names__c FROM Template_Variable_Configurations__r) FROM SMS_Template__c';
             String query = 'SELECT Name, Template_Data__c, (SELECT Type_of_Object__c, Variable_Api_Names__c FROM Template_Variable_Configurations__r) FROM SMS_Template__c Where Manual_Trigger__c = TRUE';// this need to be used only commenting for now only
            List<SMS_Template__c> templates = Database.query(query);
            // Log query results
            // System.debug('Query results: ' + templates);
            List<SMS_Template__c> filteredTemplates = new List<SMS_Template__c>();
            for(SMS_Template__c template : templates) {
                if(template.Template_Variable_Configurations__r.size() > 0) {
                    filteredTemplates.add(template);
                }
            }
            if(!filteredTemplates.isEmpty()) {
                return filteredTemplates;
            } else {
                return null;
            }
        } catch (Exception e) {
            // Log error
            System.debug('Error in getSMSTemplates: ' + e.getMessage());
            return null;
        }
    }
    @AuraEnabled(cacheable=true)
   public static String getMessage(String templateName, Id recordId) {
        try { 
            return ExotelSMSmessageCreation.createMessage(recordId, templateName);
        } catch (Exception e) {
            // Log error
            System.debug('Error in fetchRecordFields: ' + e.getMessage());
            return null;
        }
    }
    @AuraEnabled(cacheable=true)
    public static Map<String, String> getPhoneNumbers(Id recordId) {
    Map<String, String> phoneMap = new Map<String, String>();
    try {
        List<WOrkOrder> workOrders = [SELECT Case.Contact_Phone__c, Case.Contact.Phone, Case.Contact.MobilePhone,  
                                       Case.Account.Phone, Case.Contact.Account.Secondary_Phone_No__c,  
                                       Case.Contact.Account.Landline__c, Case.Contact.LastName, Case.Contact.Account.Name 
                                       FROM WOrkOrder WHERE Id = :recordId LIMIT 1];
        if (!workOrders.isEmpty()) {
            WOrkOrder order = workOrders[0];
            System.debug('Query results: ' + order);
            if (order.Case.Contact.Phone != null) {
                phoneMap.put(order.Case.Contact.Phone, order.Case.Contact.LastName);
            }
            if (order.Case.Contact.MobilePhone != null) {
                phoneMap.put(order.Case.Contact.MobilePhone, order.Case.Contact.LastName);
            }
            // if (order.Case.Contact.MobilePhone != null) {
            //     phoneMap.put(order.Contact.MobilePhone, order.Case.Contact.LastName);
            // }

            if (order.Case.Account.Phone != null) {
                phoneMap.put(order.Case.Account.Phone, order.Case.Account.Name);
            }
            if (order.Case.Contact.Account.Secondary_Phone_No__c != null) {
                phoneMap.put(order.Case.Contact.Account.Secondary_Phone_No__c, order.Case.Contact.Account.Name);
            }
            if (order.Case.Contact.Account.Landline__c != null) {
                phoneMap.put(order.Case.Contact.Account.Landline__c, order.Case.Contact.Account.Name);
            }
        }
 System.debug('Query results: ' + phoneMap);
    } catch (Exception e) {
        // Log error
        System.debug('Error in getPhoneNumbers: ' + e.getMessage());
    }

    return phoneMap;
}

//    public static List<WOrkOrder> getPhoneNumbers(Id recordId) {
//         try { 
//              List<WOrkOrder> obj = Database.query('SELECT Case.Contact_Phone__c,Case.Contact.Phone, Case.Contact.MobilePhone,  Case.Contact.Account.Phone,  Case.Contact.Account.Secondary_Phone_No__c,  Case.Contact.Account.Landline__c, Case.Contact.LastName, Case.Contact.Account.Name FROM WOrkOrder WHERE Id = \'' + recordId + '\' LIMIT 1');
//               return obj;
//         } catch (Exception e) {
//             // Log error
//             System.debug('Error in fetchRecordFields: ' + e.getMessage());
//             return null;
//         }
//     }
     @AuraEnabled(cacheable=true)
    public static String sendSMS(List<String> phoneNumber, String recordId, String templateName) {
        try {
            system.debug('sendSMS 103');
            // Null check for phoneNumber, recordId, and templateName
            if (phoneNumber == null || recordId == null || templateName == null) {
                return null;
            }
            // Call ExotelSMSAPI to send SMS
            ExotelSMSAPI.sendSMS(phoneNumber, recordId, templateName);
            return 'success';
        } catch (Exception e) {
            // Log error
            System.debug('Error in sendSMS: ' + e.getMessage());
            return null;
        }
    }
}