HVAC Backup 2/objects/Survey_Invitation__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Survey Invitations</relationshipLabel>
        <relationshipName>Survey_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Completed_Date__c</fullName>
        <label>Survey Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Invitations</relationshipLabel>
        <relationshipName>Survey_Invitations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Invitation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Survey Invitation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Invitations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HVAC Backup 2/objects/Survey_Question_Language__c.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Marathi</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question_Value__c</fullName>
        <label>Question Value</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Question Languages</relationshipLabel>
        <relationshipName>Survey_Question_Languages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Question Language</label>
    <nameField>
        <displayFormat>SQLN-{0000}</displayFormat>
        <label>Survey Question Language Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Languages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HVAC Backup 2/objects/Survey_Response__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Comment__c</fullName>
        <label>Answer Comment</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Invitation__c</fullName>
        <label>Survey Invitation</label>
        <referenceTo>Survey_Invitation__c</referenceTo>
        <relationshipLabel>Survey Response</relationshipLabel>
        <relationshipName>Survey_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Response</relationshipLabel>
        <relationshipName>Survey_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SRN-{0000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HVAC Backup 2/objects/Trigger_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Setting</label>
</CustomObject>

HVAC Backup 2/classes/SurveyFormControllerTest.cls
@isTest
private class SurveyFormControllerTest {
    @testSetup
    static void setupTestData() {
        TestDataFactory.disableTriggers();
    }
    
    @isTest
    static void testGetSurveyIdByInvitationNumber_CompletionDateNull() {
        try{
        // Create a test survey
        Survey__c testSurvey = new Survey__c(Name = 'Test Survey');
        insert testSurvey;
        
        // Create a test invitation with Survey_Completed_Date__c as null
        Survey_Invitation__c testInvitation = new Survey_Invitation__c(Survey__c = testSurvey.Id, Survey_Completed_Date__c = null);
        insert testInvitation;
        
        Survey_Invitation__c e = [SELECT name FROM Survey_Invitation__c WHERE id =:testInvitation.id];       
        
        Test.startTest();
        // Call the method being tested
        Id surveyId = SurveyFormController.getSurveyIdByInvitationNumber(e.Name);
        Test.stopTest();
        
        // Perform assertions
        System.assertEquals(testSurvey.Id, surveyId, 'Survey Id should match the test survey Id when Survey_Completed_Date__c is null');
        }catch(Exception e){

        }
    }
    
    @isTest
    static void testGetSurveyIdByInvitationNumber_CompletionDateNotNull() {
        try{
        // Create a test survey
        Survey__c testSurvey = new Survey__c(Name = 'Test Survey');
        insert testSurvey;
        
        // Create a test invitation with Survey_Completed_Date__c as today's date
        Survey_Invitation__c testInvitation = new Survey_Invitation__c(
            Survey__c = testSurvey.Id,
            Survey_Completed_Date__c = Date.today()
        );
        insert testInvitation;
        
        Test.startTest();
        // Call the method being tested
        Id nullSurveyId = SurveyFormController.getSurveyIdByInvitationNumber(testInvitation.Name);
        Test.stopTest();
        
        // Perform assertions
        System.assertEquals(null, nullSurveyId, 'Survey Id should be null when Survey_Completed_Date__c is not null');
        }catch(Exception e){

        }
    }
    
    @isTest
    static void testGetSurveyLanguages() {
        try{
        // Create a test survey record
        Survey__c testSurvey = new Survey__c(Language__c = 'English');
        insert testSurvey;
        
        Test.startTest();
        // Call the method being tested
        List<Survey__c> surveyLanguages = SurveyFormController.getSurveyLanguages(testSurvey.Id);
        Test.stopTest();
        
        // Perform assertions
        System.assertEquals(1, surveyLanguages.size(), 'Expected one survey language record');
        System.assertEquals('English', surveyLanguages[0].Language__c, 'Language should match the test survey language');
        }catch(exception e){

        }
    }
    
    @isTest
    static void testGetSurveyQuestion() {
        // Test data setup
        try{
        Survey__c testSurvey = new Survey__c(Name = 'Test Survey');
        insert testSurvey;
        
        Survey_Question__c surveyQuestion = new Survey_Question__c(Survey__c = testSurvey.id, Order__c = 3);
        insert surveyQuestion;
        
        Survey_Invitation__c testInvitation = new Survey_Invitation__c(Survey__c = testSurvey.Id);
        insert testInvitation;
        
        Survey_Question_Language__c newTranslation = new Survey_Question_Language__c(
        Survey_Question__c =surveyQuestion.Id,
        Question_Value__c = 'value', // Keep the same question value
        Language__c = 'Hindi' // Example new language
    	);
        insert newTranslation;
        
        Test.startTest();
        // Call the method being tested
        Id surveyId = SurveyFormController.getSurveyIdByInvitationNumber(testInvitation.Name);
        String result = SurveyFormController.getServiceTicketNumber(testInvitation.Name);
        List<Survey_Question__c> surveyQuestions = SurveyFormController.getSurveyQuestion('Hindi', testSurvey.Id);
        //List<SurveyQuestionWrapper> surveyQuestionWrappers = SurveyFormController.getSurveyQuestionModified('Hindi', surveyId);
        Test.stopTest();
        
        // Assertions
        //System.assertNotEquals(1, surveyQuestions.size(), 'Expected survey questions should be retrieved');
        }catch(Exception e){

        }
    }
    
    

    @isTest
    static void testSurveyTrigger() {
        // Test data setup
        try{

            Trigger_Setting__c allTriggerSetting = Trigger_Setting__c.getValues('AllTriggers');
            allTriggerSetting.IsActive__c = true;
            update allTriggerSetting;

            Trigger_Setting__c triggerSetting = Trigger_Setting__c.getValues('SurveyInvitationTrigger');
            triggerSetting.IsActive__c = true;
            update triggerSetting;

            SurveyInvitationTriggerHandler.TriggerDisabled = false;
            Account ResidentialAccount = TestDataFactory.createResidentialAccount('Survey', '9000000000');
            Case newCase = new Case(
            Origin = 'Phone',
            Status = 'In Progress',
            Subject = 'Test Subject',
            AccountId = ResidentialAccount.Id,
            Contact_Phone__c= '9000000000',
            Contact_email__c = 'test@test.com'
            );
            insert newCase;

            WorkType workType = TestDataFactory.createWorkType('Breakdown');
            WorkOrder workOrder = TestDataFactory.createWorkOrder(new Asset(), workType,ResidentialAccount , newCase,'In Progress');
        

            Survey__c testSurvey = new Survey__c(Name = 'Test Survey');
            insert testSurvey;
        
        Survey_Question__c surveyQuestion = new Survey_Question__c(Survey__c = testSurvey.id, Order__c = 3);
        insert surveyQuestion;
        
        Survey_Invitation__c testInvitation = new Survey_Invitation__c(Survey__c = testSurvey.Id, case__c = newCase.Id);
        insert testInvitation;

        testInvitation.case__c = null;
        update testInvitation;
        
        Survey_Question_Language__c newTranslation = new Survey_Question_Language__c(
        Survey_Question__c =surveyQuestion.Id,
        Question_Value__c = 'value', // Keep the same question value
        Language__c = 'Hindi' // Example new language
    	);
        insert newTranslation;
        
        Test.startTest();
        // Call the method being tested
        Id surveyId = SurveyFormController.getSurveyIdByInvitationNumber(testInvitation.Name);
        delete testInvitation;
        undelete testInvitation;
        Test.stopTest();
        
        // Assertions
        //System.assertNotEquals(1, surveyQuestions.size(), 'Expected survey questions should be retrieved');
        }catch(Exception e){

        }
    }

    @isTest
    static void testSurveyQuestionWrapper() {
        // Test data setup
        try{
        Survey__c testSurvey = new Survey__c(Name = 'Test Survey');
        insert testSurvey;
        
        Survey_Question__c surveyQuestion1 = new Survey_Question__c(Survey__c = testSurvey.id, Order__c = 1, Answer_Type__c='Text');
        SurveyQuestionWrapper wrapper = new SurveyQuestionWrapper(surveyQuestion1);
        Survey_Question__c surveyQuestion2 = new Survey_Question__c(Survey__c = testSurvey.id, Order__c = 2, Answer_Type__c='Long Text');
        wrapper = new SurveyQuestionWrapper(surveyQuestion2);
        Survey_Question__c surveyQuestion3 = new Survey_Question__c(Survey__c = testSurvey.id, Order__c = 3, Answer_Type__c='Rating');
        wrapper = new SurveyQuestionWrapper(surveyQuestion3);
        Survey_Question__c surveyQuestion4 = new Survey_Question__c(Survey__c = testSurvey.id, Order__c = 4, Answer_Type__c='Radio');
        wrapper = new SurveyQuestionWrapper(surveyQuestion4);
        Survey_Question__c surveyQuestion5 = new Survey_Question__c(Survey__c = testSurvey.id, Order__c = 5, Answer_Type__c='Checkbox');
        wrapper = new SurveyQuestionWrapper(surveyQuestion5);
        Survey_Question__c surveyQuestion6 = new Survey_Question__c(Survey__c = testSurvey.id, Order__c = 6, Answer_Type__c='Dropdown');
        wrapper = new SurveyQuestionWrapper(surveyQuestion6);
        Survey_Question__c surveyQuestion7 = new Survey_Question__c(Survey__c = testSurvey.id, Order__c = 7, Answer_Type__c='Button');
        wrapper = new SurveyQuestionWrapper(surveyQuestion7);
        
        
        }catch(Exception e){

        }
    }
	@isTest
	static void testSaveSurveyResponses() {
   
    Survey__c testSurvey = new Survey__c(Language__c = 'English');
    insert testSurvey;

   
    Survey_Invitation__c testInvitation = new Survey_Invitation__c(Survey__c = testSurvey.Id);
    insert testInvitation;

   
    Survey_Question__c questionLongText = new Survey_Question__c(
        Survey__c = testSurvey.Id,
        Answer_Type__c = 'Long Text',
        Order__c = 1
    );
    Survey_Question__c questionShortText = new Survey_Question__c(
        Survey__c = testSurvey.Id,
        Answer_Type__c = 'Text',
        Order__c = 2
    );
    insert new List<Survey_Question__c>{ questionLongText, questionShortText };

    
    Survey_Invitation__c invitation = [SELECT Name FROM Survey_Invitation__c WHERE Id = :testInvitation.Id];

   
    SurveyFormResponseWrapper r1 = new SurveyFormResponseWrapper();
    r1.questionId = questionLongText.Id;
    r1.answer = 'Initial Long Text';

    SurveyFormResponseWrapper r2 = new SurveyFormResponseWrapper();
    r2.questionId = questionShortText.Id;
    r2.answer = 'Initial Short Text';

    
    SurveyFormResponseWrapper r3 = new SurveyFormResponseWrapper();
    r3.questionId = questionLongText.Id;
    r3.answer = 'Updated Long Text';

    Test.startTest();
    
    SurveyFormController.saveSurveyResponses(new List<SurveyFormResponseWrapper>{ r1, r2 }, invitation.Name);
    
    SurveyFormController.saveSurveyResponses(new List<SurveyFormResponseWrapper>{ r3 }, invitation.Name);
    Test.stopTest();

   
    List<Survey_Response__c> responses = [
        SELECT Id, Answer__c, Answer_Comment__c, Survey_Question__c 
        FROM Survey_Response__c 
        WHERE Survey_Invitation__c = :testInvitation.Id
    ];
    System.assertEquals(2, responses.size(), 'Should have 2 responses saved');

   
    Survey_Response__c updated = [
        SELECT Answer__c, Answer_Comment__c 
        FROM Survey_Response__c 
        WHERE Survey_Question__c = :questionLongText.Id 
        AND Survey_Invitation__c = :testInvitation.Id 
        LIMIT 1
    ];
    System.assertEquals('Updated Long Text', updated.Answer_Comment__c, 'Long text answer should be updated');

  
    Survey_Invitation__c updatedInvitation = [
        SELECT Survey_Completed_Date__c 
        FROM Survey_Invitation__c 
        WHERE Id = :testInvitation.Id
    ];
    System.assertNotEquals(null, updatedInvitation.Survey_Completed_Date__c, 'Survey should be marked completed');
	}


}